export const ADD_ITEM = 'ADD_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const DELET_ITEM = 'DELET_ITEM';
export const CHANGE_ACTION_PRISE = 'CHANGE_ACTION_PRISE';
export const CLEAR_FIELDS = 'CLEAR_FIELDS';
export const INSERTING_ITEM_INTO_FORM = 'INSERTING_ITEM_INTO_FORM';
export const CHANGE_FILTER_VALUE = 'CHANGE_FILTER_VALUE';
